import re
import codecs

# Read the UTF-16 LE file generated by PowerShell
try:
    with codecs.open('backend/app/seed_data.py', 'r', encoding='utf-16le') as f:
        seed_data_content = f.read()
except Exception:
    with open('backend/app/seed_data.py', 'r', encoding='utf-8') as f:
        seed_data_content = f.read()

# Fix the seed file if it has null bytes
with open('backend/app/seed.py', 'rb') as f:
    raw = f.read()

# Convert from whatever it is to normal string
try:
    if b'\x00' in raw:
        seed_content = raw.decode('utf-16le')
    else:
        seed_content = raw.decode('utf-8')
except Exception:
    seed_content = raw.decode('utf-8', errors='ignore')

# Remove null bytes just in case
seed_content = seed_content.replace('\x00', '')

# Replace PRODUCTS again just to be safe
seed_content = re.sub(r'PRODUCTS = \[\s*(?:.|\n)*?\]\n', seed_data_content + '\n', seed_content, count=1)

with codecs.open('backend/app/seed.py', 'w', encoding='utf-8') as f:
    f.write(seed_content)
