/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         *     Returns 200 if the API is up and DB is reachable.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Categories
         * @description Returns the hierarchical category tree (root categories with nested children).
         */
        get: operations["get_categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Products
         * @description Returns a paginated, filtered, sorted list of products with metadata.
         */
        get: operations["get_products_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product Detail
         * @description Returns full product details along with related products.
         */
        get: operations["get_product_detail_api_products__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{slug}/variants/{variant_id}/price": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Variant Price
         * @description Returns calculated pricing breakdown for a specific variant & quantity.
         */
        get: operations["get_variant_price_api_products__slug__variants__variant_id__price_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Catalog
         * @description Search product catalog using PostgreSQL Full-Text Search.
         *     Falls back to RapidFuzz fuzzy matcher in-memory cache if fewer than 3 results are found.
         *     Rate limited to 30 requests per minute per IP.
         */
        get: operations["search_catalog_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Addresses */
        get: operations["list_addresses_api_addresses_get"];
        put?: never;
        /** Create Address */
        post: operations["create_address_api_addresses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/addresses/{address_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Address */
        delete: operations["delete_address_api_addresses__address_id__delete"];
        options?: never;
        head?: never;
        /** Update Address */
        patch: operations["update_address_api_addresses__address_id__patch"];
        trace?: never;
    };
    "/api/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cart */
        get: operations["get_cart_api_cart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Cart Item */
        post: operations["add_cart_item_api_cart_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Cart Item */
        delete: operations["delete_cart_item_api_cart_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Cart Item */
        patch: operations["update_cart_item_api_cart_items__item_id__patch"];
        trace?: never;
    };
    "/api/cart/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Cart */
        post: operations["merge_cart_api_cart_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order Detail */
        get: operations["get_order_detail_api_orders__order_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Order Status */
        patch: operations["update_order_status_api_orders__order_id__status_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressCreate */
        AddressCreate: {
            /**
             * Label
             * @default Home
             */
            label: string;
            /** Full Address */
            full_address: string;
            /** City */
            city: string;
            /** State */
            state: string;
            /** Pincode */
            pincode: string;
            /** Phone */
            phone?: string | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** AddressRead */
        AddressRead: {
            /**
             * Label
             * @default Home
             */
            label: string;
            /** Full Address */
            full_address: string;
            /** City */
            city: string;
            /** State */
            state: string;
            /** Pincode */
            pincode: string;
            /** Phone */
            phone?: string | null;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AddressUpdate */
        AddressUpdate: {
            /** Label */
            label?: string | null;
            /** Full Address */
            full_address?: string | null;
            /** City */
            city?: string | null;
            /** State */
            state?: string | null;
            /** Pincode */
            pincode?: string | null;
            /** Phone */
            phone?: string | null;
            /** Is Default */
            is_default?: boolean | null;
        };
        /** BrandRead */
        BrandRead: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Logo Url */
            logo_url?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CartItemAdd */
        CartItemAdd: {
            /** Variant Id */
            variant_id: number;
            /** Quantity */
            quantity: number;
        };
        /** CartItemRead */
        CartItemRead: {
            /** Id */
            id: number;
            /** Cart Id */
            cart_id: number;
            /** Variant Id */
            variant_id: number;
            /** Quantity */
            quantity: number;
            /** Price Snapshot */
            price_snapshot?: number | null;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            live_price?: components["schemas"]["PriceBreakdown"] | null;
            /** Product Name */
            product_name?: string | null;
            /** Sku */
            sku?: string | null;
            /** Size Label */
            size_label?: string | null;
            /** Primary Image Url */
            primary_image_url?: string | null;
        };
        /** CartItemUpdate */
        CartItemUpdate: {
            /** Quantity */
            quantity: number;
        };
        /** CartMergeRequest */
        CartMergeRequest: {
            /** Session Token */
            session_token?: string | null;
        };
        /** CartRead */
        CartRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id?: number | null;
            /** Session Token */
            session_token?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["CartItemRead"][];
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
            /**
             * Subtotal
             * @default 0
             */
            subtotal: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CategoryRead */
        CategoryRead: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Parent Id */
            parent_id?: number | null;
            /** Image Url */
            image_url?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CategoryTree
         * @description Category with nested children for hierarchical responses.
         */
        CategoryTree: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Parent Id */
            parent_id?: number | null;
            /** Image Url */
            image_url?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["CategoryTree"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * OrderCreate
         * @description Request body for creating an order from the current cart.
         */
        OrderCreate: {
            /** Shipping Address Id */
            shipping_address_id: number;
        };
        /** OrderItemRead */
        OrderItemRead: {
            /** Id */
            id: number;
            /** Variant Id */
            variant_id?: number | null;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number;
            /** Total Price */
            total_price: number;
            /** Product Name Snapshot */
            product_name_snapshot?: string | null;
            /** Sku Snapshot */
            sku_snapshot?: string | null;
            /** Size Label Snapshot */
            size_label_snapshot?: string | null;
        };
        /** OrderRead */
        OrderRead: {
            /** Id */
            id: number;
            /** Order Number */
            order_number: string;
            status: components["schemas"]["OrderStatus"];
            payment_status: components["schemas"]["PaymentStatus"];
            /** Shipping Address Id */
            shipping_address_id?: number | null;
            /** Subtotal */
            subtotal: number;
            /** Shipping Cost */
            shipping_cost: number;
            /** Total */
            total: number;
            /** Razorpay Order Id */
            razorpay_order_id?: string | null;
            /** Awb Code */
            awb_code?: string | null;
            /** Courier Name */
            courier_name?: string | null;
            /** Tracking Status */
            tracking_status?: string | null;
            /** Estimated Delivery */
            estimated_delivery?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["OrderItemRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "pending_payment" | "pending" | "confirmed" | "processing" | "shipped" | "delivered" | "cancelled";
        /**
         * OrderStatusUpdate
         * @description Admin-only: update order status.
         */
        OrderStatusUpdate: {
            status: components["schemas"]["OrderStatus"];
        };
        /**
         * PaymentStatus
         * @enum {string}
         */
        PaymentStatus: "pending" | "paid" | "failed" | "refunded" | "partially_refunded";
        /**
         * PriceBreakdown
         * @description Returned by the pricing service for a given variant + quantity combination.
         */
        PriceBreakdown: {
            /** Variant Id */
            variant_id: number;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number;
            /** Total Price */
            total_price: number;
            /** Mrp */
            mrp: number;
            /** Wholesale Price */
            wholesale_price?: number | null;
            /** Wholesale Min Qty */
            wholesale_min_qty?: number | null;
            /** Tier Applied */
            tier_applied: string;
            /**
             * Savings Amount
             * @default 0
             */
            savings_amount: number;
            /**
             * Savings Percentage
             * @default 0
             */
            savings_percentage: number;
            /** Wholesale Units Away */
            wholesale_units_away?: number | null;
        };
        /** ProductAttributeRead */
        ProductAttributeRead: {
            /** Product Id */
            product_id: number;
            /** Attribute Name */
            attribute_name: string;
            /** Attribute Value */
            attribute_value: string;
            /** Id */
            id: number;
        };
        /** ProductDetailResponse */
        ProductDetailResponse: {
            product: components["schemas"]["ProductRead"];
            /** Related Products */
            related_products: components["schemas"]["ProductListItem"][];
        };
        /** ProductImageRead */
        ProductImageRead: {
            /** Product Id */
            product_id: number;
            /** Variant Id */
            variant_id?: number | null;
            /** Image Url */
            image_url: string;
            /** Alt Text */
            alt_text?: string | null;
            /**
             * Display Order
             * @default 0
             */
            display_order: number;
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
            /** Id */
            id: number;
        };
        /**
         * ProductListItem
         * @description Lightweight product schema for list/grid views — no variants detail, just price range.
         */
        ProductListItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Component Type */
            component_type?: string | null;
            /** Material */
            material?: string | null;
            /** Pressure Rating */
            pressure_rating?: string | null;
            /** Is Active */
            is_active: boolean;
            category?: components["schemas"]["CategoryRead"] | null;
            brand?: components["schemas"]["BrandRead"] | null;
            /** Primary Image Url */
            primary_image_url?: string | null;
            /** Min Price */
            min_price?: number | null;
            /** Max Price */
            max_price?: number | null;
            /**
             * Variant Count
             * @default 0
             */
            variant_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProductRead */
        ProductRead: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** Brand Id */
            brand_id?: number | null;
            /** Component Type */
            component_type?: string | null;
            /** Material */
            material?: string | null;
            /** Pressure Rating */
            pressure_rating?: string | null;
            /** Meta Title */
            meta_title?: string | null;
            /** Meta Description */
            meta_description?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            category?: components["schemas"]["CategoryRead"] | null;
            brand?: components["schemas"]["BrandRead"] | null;
            /**
             * Variants
             * @default []
             */
            variants: components["schemas"]["ProductVariantRead"][];
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["ProductImageRead"][];
            /**
             * Attributes
             * @default []
             */
            attributes: components["schemas"]["ProductAttributeRead"][];
        };
        /** ProductVariantRead */
        ProductVariantRead: {
            /** Sku */
            sku: string;
            /** Size Label */
            size_label?: string | null;
            /** Size Dimensions */
            size_dimensions?: Record<string, never> | null;
            /** Dimensions Cm */
            dimensions_cm?: Record<string, never> | null;
            /** Weight Grams */
            weight_grams?: number | null;
            /** Mrp */
            mrp: number;
            /** Wholesale Price */
            wholesale_price?: number | null;
            /** Wholesale Min Qty */
            wholesale_min_qty?: number | null;
            /**
             * Stock Quantity
             * @default 0
             */
            stock_quantity: number;
            /**
             * Low Stock Threshold
             * @default 10
             */
            low_stock_threshold: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: number;
            /** Product Id */
            product_id: number;
            /** Reserved Quantity */
            reserved_quantity: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["ProductImageRead"][];
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["ProductListItem"][];
            /** Fuzzy Fallback Used */
            fuzzy_fallback_used: boolean;
            /** Query */
            query: string;
        };
        /** TokenRefreshRequest */
        TokenRefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Is Admin */
            is_admin: boolean;
            /** Is Wholesale Customer */
            is_wholesale_customer: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Addresses
             * @default []
             */
            addresses: components["schemas"]["AddressRead"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryTree"][];
                };
            };
        };
    };
    get_products_api_products_get: {
        parameters: {
            query?: {
                /** @description Filter by Category ID */
                category_id?: number | null;
                /** @description Filter by Brand ID */
                brand_id?: number | null;
                /** @description Filter by Component Type */
                component_type?: string | null;
                /** @description Filter by Pressure Rating */
                pressure_rating?: string | null;
                /** @description Filter by Material */
                material?: string | null;
                /** @description Filter by Minimum MRP */
                min_price?: number | null;
                /** @description Filter by Maximum MRP */
                max_price?: number | null;
                /** @description Sort by: price_asc, price_desc, newest, name_asc */
                sort_by?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_detail_api_products__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_variant_price_api_products__slug__variants__variant_id__price_get: {
        parameters: {
            query?: {
                quantity?: number;
            };
            header?: never;
            path: {
                slug: string;
                variant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceBreakdown"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_catalog_api_search_get: {
        parameters: {
            query: {
                /** @description Search query string */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_addresses_api_addresses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressRead"][];
                };
            };
        };
    };
    create_address_api_addresses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_address_api_addresses__address_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_address_api_addresses__address_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cart_api_cart_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cart_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_cart_item_api_cart_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cart_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_cart_item_api_cart_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: {
                cart_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_cart_item_api_cart_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: {
                cart_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_cart_api_cart_merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                cart_session?: string | null;
            };
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CartMergeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_orders_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_detail_api_orders__order_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_status_api_orders__order_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
